openapi: 3.1.0
info:
  title: STEL Order API - Albaranes Simulado (Mock Data)
  version: 1.0.0
  description: Acción simulada para buscar albaranes de trabajo.

servers:
  - url: https://fake.stelorder.local

paths:
  /workDeliveryNotes:
    get:
      summary: Buscar albaranes de trabajo (Mock)
      operationId: getWorkDeliveryNotes
      x-openai-isMock: true
      x-openai-data:
        albaranes:
          - id: 98765
            title: "412029438/0010"
            cliente: "WashTec España S.L."
            estado: "Pendiente de facturar"
            fecha: "2025-07-25"
            total: 154.90
          - id: 98766
            title: "412029439/0010"
            cliente: "WashTec España S.L."
            estado: "Planificado"
            fecha: "2025-07-28"
            total: 240.00
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: Número de orden o título del albarán
      responses:
        '200':
          description: Lista de albaranes simulada 
