openapi: 3.1.0
info:
  title: STEL Order API - Simulado
  version: 1.0.0
  description: Acción simulada para buscar albaranes de trabajo.

servers:
  - url: https://fake.stelorder.local

paths:
  /workOrders:
    get:
      summary: Buscar albaranes de trabajo (Simulado)
      operationId: getWorkOrders
      x-openai-isMock: true
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: Número de orden o título del albarán
      responses:
        '200':
          description: Lista de albaranes simulada
          content:
            application/json:
              example:
                albaranes:
                  - id: 98765
                    title: "412029438/0010"
                    cliente: "WashTec España S.L."
                    estado: "Pendiente de facturar"
                    fecha: "2025-07-25"
                    total: 154.90
                  - id: 98766
                    title: "412029439/0010"
                    cliente: "WashTec España S.L."
                    estado: "Planificado"
                    fecha: "2025-07-28"
                    total: 240.00

