openapi: 3.1.0
info:
  title: STEL Order API
  version: 1.0.0
  description: Consulta de albaranes de trabajo

servers:
  - url: https://app.stelorder.com/app

paths:
  /workOrders:
    get:
      summary: Obtener lista de albaranes de trabajo
      operationId: getWorkDeliveryNotes
      security:
        - ApiKeyAuth: []
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: Filtrar por título del albarán
      responses:
        '200':
          description: Lista de albaranes
          content:
            application/json:
              schema:
                type: object
                properties:
                  workOrders:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        total:
                          type: number
                        estado:
                          type: string

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization 
