openapi: 3.1.0
info:
  title: STEL Order API
  version: 1.0.0
  description: API para gestionar facturas, incidencias, clientes, albaranes y presupuestos.

servers:
  - url: https://app.stelorder.com/app/indexapi.html

paths:
  /clients:
    get:
      summary: Obtener lista de clientes
      operationId: getClients
      responses:
        '200':
          description: Lista de clientes

  /invoices:
    get:
      summary: Obtener lista de facturas
      operationId: getInvoices
      responses:
        '200':
          description: Lista de facturas

  /workOrders:
    get:
      summary: Obtener lista de albaranes de trabajo
      operationId: getWorkOrders
      responses:
        '200':
          description: Lista de albaranes

  /incidences:
    get:
      summary: Obtener lista de incidencias
      operationId: getIncidences
      responses:
        '200':
          description: Lista de incidencias

  /quotes:
    get:
      summary: Obtener lista de presupuestos
      operationId: getQuotes
      responses:
        '200':
          description: Lista de presupuestos

