openapi: 3.1.0
info:
  title: STEL Order API Integration
  version: 1.0.1
  description: |
    Integración con la API de STEL Order para gestionar albaranes de trabajo.
    Todas las peticiones deben incluir el header: APIKEY: 0RjnBmi37UswuylVpjIyi7I6gvX54i2ShBnJLsC0
servers:
  - url: https://api.stelorder.com
paths:
  /workDeliveryOrders/search:
    get:
      summary: Buscar albaranes de trabajo
      operationId: searchWorkOrders
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
        - name: orderNumber
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Lista de albaranes encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/WorkOrder"
                  count:
                    type: integer
  /workDeliveryOrders/{id}:
    get:
      summary: Detalles del albarán
      operationId: getWorkOrderDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalles del albarán
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkOrder"
  /workDeliveryOrders/pending:
    get:
      summary: Albaranes pendientes de facturar
      operationId: listPendingWorkOrders
      parameters:
        - name: documentStateId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Albaranes pendientes
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/WorkOrder"
                  count:
                    type: integer
  /workDeliveryOrders:
    post:
      summary: Crear nuevo albarán
      operationId: createWorkOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewWorkOrder"
      responses:
        "201":
          description: Albarán creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkOrder"
  /workDeliveryOrders/{id}/attachments:
    post:
      summary: Subir adjunto a un albarán
      operationId: uploadWorkOrderAttachment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: Archivo adjunto subido
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  filename:
                    type: string
                  url:
                    type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: APIKEY
  schemas:
    WorkOrder:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        client:
          type: string
        total:
          type: number
        date:
          type: string
        status:
          type: string
        documentStateId:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/WorkOrderItem"
    WorkOrderItem:
      type: object
      properties:
        description:
          type: string
        quantity:
          type: number
        unitPrice:
          type: number
        total:
          type: number
    NewWorkOrder:
      type: object
      required:
        - title
        - client
        - date
      properties:
        title:
          type: string
        client:
          type: string
        date:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/WorkOrderItem"
        notes:
          type: string
