openapi: 3.1.0
info:
  title: STEL Order API - Albaranes reales
  version: 1.0.0
  description: Permite buscar albaranes de trabajo reales desde STEL Order.

servers:
  - url: https://app.stelorder.com/app

paths:
  /workOrders:
    get:
      summary: Obtener lista de albaranes de trabajo
      operationId: getWorkOrders
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: Filtrar albaranes por título (número de orden)
      responses:
        '200':
          description: Lista de albaranes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbaranResponse'
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Albaran:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        cliente:
          type: string
        estado:
          type: string
        fecha:
          type: string
        total:
          type: number
      required:
        - id
        - title

    AlbaranResponse:
      type: object
      properties:
        albaranes:
          type: array
          items:
            $ref: '#/components/schemas/Albaran'
