openapi: 3.1.0
info:
  title: STEL Order API Integration
  version: 1.0.0
  description: |
    Esta especificación OpenAPI define los endpoints usados por el agente GPT
    para interactuar con el servicio STEL Order. Permite buscar albaranes, 
    obtener detalles, listar albaranes pendientes de facturar, subir adjuntos y crear albaranes.
    Todas las peticiones deben incluir la clave de API de STEL Order en la cabecera `APIKEY` sin prefijo.

servers:
  - url: https://app.stelorder.com/app

paths:
  /workDeliveryOrders/search:
    get:
      summary: Buscar albaranes de trabajo
      operationId: searchWorkOrders
      parameters:
        - name: title
          in: query
          description: Buscar por título del albarán.
          required: false
          schema:
            type: string
        - name: orderNumber
          in: query
          description: Buscar por número de orden interna.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Lista de albaranes coincidentes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/WorkOrder"
                  count:
                    type: integer
        "400":
          description: Parámetros inválidos.
      security:
        - ApiKeyAuth: []

  /workDeliveryOrders/{id}:
    get:
      summary: Obtener detalles del albarán
      operationId: getWorkOrderDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalles del albarán.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkOrder"
        "404":
          description: No encontrado.
      security:
        - ApiKeyAuth: []

  /workDeliveryOrders/pending:
    get:
      summary: Listar albaranes pendientes de facturar
      operationId: listPendingWorkOrders
      parameters:
        - name: documentStateId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Lista de albaranes pendientes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/WorkOrder"
                  count:
                    type: integer
        "400":
          description: Parámetros inválidos.
      security:
        - ApiKeyAuth: []

  /workDeliveryOrders/{id}/attachments:
    post:
      summary: Subir adjunto a albarán
      operationId: uploadWorkOrderAttachment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: Adjunto subido correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  filename:
                    type: string
                  url:
                    type: string
        "404":
          description: Albarán no encontrado.
        "415":
          description: Formato no soportado.
      security:
        - ApiKeyAuth: []

  /workDeliveryOrders:
    post:
      summary: Crear albarán de trabajo
      operationId: createWorkOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewWorkOrder"
      responses:
        "201":
          description: Albarán creado correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkOrder"
        "400":
          description: Payload inválido.
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: APIKEY
      description: |
        Todas las solicitudes deben incluir la clave API en el encabezado `APIKEY`.
        Ejemplo:
        APIKEY: 0RjnBmi37UswuylVpjIyi7I6gvX54i2ShBnJLsC0

  schemas:
    WorkOrder:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        client:
          type: string
        total:
          type: number
          format: float
        date:
          type: string
          format: date
        status:
          type: string
        documentStateId:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/WorkOrderItem"

    WorkOrderItem:
      type: object
      properties:
        description:
          type: string
        quantity:
          type: number
          format: float
        unitPrice:
          type: number
          format: float
        total:
          type: number
          format: float

    NewWorkOrder:
      type: object
      required:
        - title
        - client
        - date
      properties:
        title:
          type: string
        client:
          type: string
        date:
          type: string
          format: date
        items:
          type: array
          items:
            $ref: "#/components/schemas/WorkOrderItem"
        notes:
          type: string
