openapi: 3.1.0
info:
  title: STEL Order API - Albaranes reales
  version: 1.0.0
  description: Permite buscar albaranes de trabajo reales desde STEL Order.

servers:
  - url: https://app.stelorder.com/app

paths:
  /workOrders:
    get:
      summary: Obtener lista de albaranes de trabajo
      operationId: getWorkOrders
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
          description: Filtrar albaranes por título (número de orden)
      responses:
        '200':
          description: Lista de albaranes
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 12345
                  title: "412029438/0010"
                  cliente: "WashTec España S.L."
                  estado: "Pendiente de facturar"
                  fecha: "2025-07-25"
                  total: 154.90
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

